sudo: required
services:
  - docker

before_install:
  - docker build -t jazz9008/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jazz9008/react-test npm test -- --coverage

after_success:
  - docker build -t jazz9008/multi-client ./client
  - docker build -t jazz9008/multi-nginx ./nginx
  - docker build -t jazz9008/multi-server ./server
  - docker build -t jazz9008/multi-worker ./worker
  #333
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  #444
  - docker push jazz9008/multi-client
  - docker push jazz9008/multi-nginx
  - docker push jazz9008/multi-server
  - docker push jazz9008/multi-worker