sudo: required
services:
  - docker

before_install:
  - docker build -t youngwonseo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run youngwonseo/react-test npm test -- --coverage

after_success:
  - docker build -t youngwonseo/multi-client ./client
  - docker build -t youngwonseo/multi-nginx ./nginx
  - docker build -t youngwonseo/multi-server ./server
  - docker build -t youngwonseo/multi-worker ./worker
  #333
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  #444
  - docker push youngwonseo/multi-client
  - docker push youngwonseo/multi-nginx
  - docker push youngwonseo/multi-server
  - docker push youngwonseo/multi-worker